trigger:
- main

pool:
  name: window
  demands:
  - Agent.Name -equals agent-window

steps:
- script: echo Hello from Windows Self-Hosted Agent
  displayName: 'Hello World'

- script: hostname
  displayName: 'Check Hostname'
